server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_db
    username: root
    password: root
    driver-class-name: com.example.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
flyway:
  baseline-on-migrate: true
  locations: db/migration